const mongoose = require('mongoose');

const ContactSchema = new mongoose.Schema({
  Email: { type: String, default: null },
  currency_symbol: { type: String, default: null },
  Other_Phone: { type: String, default: null },
  Mailing_State: { type: String, default: null },
  Other_State: { type: String, default: null },
  Other_Country: { type: String, default: null },
  Department: { type: String, default: null },
  process_flow: { type: String, default: null },
  Assistant: { type: String, default: null },
  Exchange_Rate: { type: String, default: null },
  Currency: { type: String, default: null },
  Mailing_Country: { type: String, default: null },
  Data_Processing_Basis_Details: { type: String, default: null },
  Data_Source: { type: String, default: null },
  approved: { type: String, default: null },
  Reporting_To: {
    name: { type: String, default: null },
  },
  approval: {
    delegate: { type: Boolean, default: false },
    approve: { type: Boolean, default: false },
    reject: { type: Boolean, default: false },
    resubmit: { type: Boolean, default: false },
  },
  First_Visited_UR: { type: String, default: null },
  Days_Visited: { type: String, default: null },
  Other_City: { type: String, default: null },
  Negative_Touch_Point_Score: { ttype: Number, default: 0 },
  data_source_details: { type: String, default: 'R$' },
  Created_Time: { type: Date, default: Date.now },
  editable: { type: Boolean, default: true },
  Positive_Touch_Point_Score: { ttype: Number, default: 0 },
  Home_Phone: { type: String, default: null},
  Score: { type: Number, default: 0 },
  Negative_Score: { type: Number, default: 0 },
  Secondary_Email: { type: String, default: null },
  Touch_Point_Score: { type: Number, default: 0 },
  Positive_Score: { type: Number, default: 0 },
  Description: { type: String, default: null },
  Vendor_Name: {
    name: { type: String, default: null },
  },
  Mailing_Zip: { type: String, default: null },
  Number_Of_Chats: { type: String, default: null },
  review_process: {
    approve: { type: Boolean, default: false },
    reject: { type: Boolean, default: false },
    resubmit: { type: Boolean, default: false },
  },
  Twitter: { type: String, default: null },
  Other_Zip: { type: String, default: null },
  Mailing_Street: { type: String, default: null },
  Salutation: { type: String, default: null },
  First_Name: { type: String, default: null },
  Full_Name: { type: String, default: null },
  Asst_Phone: { type: String, default: null },
  Record_Image: { type: String, default: null },
  review: { type: String, default: null },
  Skype_ID: { type: String, default: null },
  Phone: { type: String, default: null },
  Account_Name: {
    name: { type: String, default: null },
  },
  Email_Opt_Out: { type: Boolean, default: true },
  Date_of_Birth: { type: Date },
  Mailing_City: { type: String, default: null },
  Title: { type: String, default: null },
  Other_Street: { type: String, default: null },
  Mobile: { type: String, default: null },
  Territories: { type: Array, default: null },
  orchestration: { type: Boolean, default: true },
  stop_processing: { type: Boolean, default: true },
  Last_Name: { type: String, required: true },
  Layout: {
    name: { type: String, default: null },
  },
  in_merge: { type: Boolean, default: false },
  Referrer: { type: Boolean, default: false },
  Lead_Source: { type: String, default: null },
  Tag: { type: Array, default: [] },
  Fax: { type: String, default: null },
  approval_state: { type: Boolean, default: false },
});

const ContactModel = mongoose.model('Contact', ContactSchema);

module.exports = ContactModel;
